[package]
name = "gcp-vertex-ai-generative-language"
version = "0.1.2"
description = "An async client library for GCP Vertex AI Generative models - Language"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true
edition.workspace = true

[features]
default = ["tls-ring"]
# unstable API - may change in future versions
unstable = []
tls-ring = ["tonic/tls-ring"]
tls-aws-lc = ["tonic/tls-aws-lc"]

[lib]
doctest = false

[dependencies]
tonic = { version = "0.14", features = [] }
tonic-prost = "0.14"
prost = "0.14"
prost-types = "0.14"
tokio = "1"
thiserror = "2"

[build-dependencies]
tonic-prost-build = { version = "0.14", features = ["cleanup-markdown"] }

[dev-dependencies]
insta = { version = "1", features = ["json"] }
tokio-test = "0.4"

[package.metadata.cargo-machete]
ignored = ["prost", "prost-types"]
